GTF: "reference/gencode.v36.primary_assembly.annotation.gtf" # Assigns path to .gtf file

INDEX_STAR: "/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/reference/star_index" # Assigns path to star indexing directory (ABSOLUTE PATH NEEDED due to a potential STAR error!)

INDEX_HISAT: "reference/hisat2_index" # Assigns path to hisat2 indexing directory

THREADS: 8     # Assigns the number of threads

STAR_OUT: "star_output"  # Assigns STAR output directory

HISAT2_OUT: "hisat2_output"  # Assigns HISAT2 output directory

INPUT_PATH: # Assigns input fastq.gz file path (either absolute or relative paths)
  - 'fastq/A_1.fastq.gz'
  - 'fastq/B_1.fastq.gz'
  
# - '/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/fastq/A_1.fastq.gz'
# - '/home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/fastq/B_1.fastq.gz'




FILE_NAME:   # Assigns file names needed as prefix
  - "A_1.fastq.gz"
  - "B_1.fastq.gz"

# /home/mira/Documents/programming/Bioinformatics/snakemake_star_hisat/.snakemake/log/2021-04-12T225244.175386.snakemake.log

